FROM microsoft/dotnet:2.2-sdk AS installer-env

ENV ASPNETCORE_ENVIRONMENT Development

FROM mcr.microsoft.com/azure-functions/dotnet:2.0
ENV AzureWebJobsScriptRoot /home/site/wwwroot
EXPOSE 80
COPY /bin/Debug/netcoreapp3.0 /home/site/wwwroot
